apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: pihole
  type: NodePort
